### ISSUE TITLE
Add docker configuration

### ISSUE THREAD

**Issue by NerdyProjects** [foodsharing-dev/foodsharing-django-api#5]
Existing foodsharing site provides a docker-compose development environment.

As this one can be installed so much easier (for now - e.g. not including dependencies like the nodejs chat server), it might be an overkill, but it could still provide a nice experience.

**Comment by nicksellen** [comment]
We should add it to the existing foodsharing docker compose setup so you only need one thing to get going (as we can also add the foodsharing light api into it too)

**Comment by NerdyProjects** [comment]
This is done and merged.
